### PR TITLE
format w/ prettier

### PR DESCRIPTION
**Pull request by jasonLaster**
this is a one time [prettier][p] pass to help w/ tabs and other formatting.

[p]: https://prettier.io/

### CODE REVIEW

**Comment by igoradamenko** [comment]
Hello again!

Thanks, I'll merge it. 

But actually I have not improved this package for a long time, because I thought that nobody uses it. Now I see that npm package is downloaded more than 1k times in the last month, so I should to rewrite a package using ES6, babel and so on, to make it cleaner and nicer.

Thank you for pushing me to do that ;)

**Comment by jasonLaster** [comment]
hey! that's great to hear. I love the simplicity of postcss plugins. it's easy to read, ....

I'd love to see some JEST tests too :)  

Happy to help maintain the project too

**Comment by jasonLaster** [comment]
wow - great work today!

**Comment by igoradamenko** [comment]
> I'd love to see some JEST tests too :)

I'm not sure that Jest is the best tool for unit testing. Actually, for me it looks like a testing tool for React. But I've not used it at all.

But right now tests look like a shit, yeah. So I will try to rewrite it in weekend using Jest, Mocha or something else. I've created #8 as a reminder :-)

**Pull request merged**
